### ISSUE TITLE
Final Milestone: Kanban Board

### ISSUE THREAD

**Issue by NickEmma** [NickEmma/car-rental-api#17]
### Project link [here](https://github.com/users/NickEmma/projects/7/views/1)
**Our collaboration consists of 5 members split into two main groups:**

### Front-End

_@NickEmma 
@AACHOURMOHAMED_ 

### Back-End

_@amejid 
@Abel-desu_ 
_@Said-laasri_ 

### Points Per Coder
@amejid = 8.0
@AACHOURMOHAMED = 8.0
@NickEmma = 8.0
@Abel-desu = 8.0
@Said-laasri = 8.0

![issue1](https://user-images.githubusercontent.com/100702612/203752985-91534730-bce9-449f-959c-1f229b9ecb8c.png)

![issue2](https://user-images.githubusercontent.com/100702612/203753007-d413f48a-0470-4841-88f1-fd2d69fd0c4a.png)

**Comment by Meltrust** [comment]
Hi @NickEmma

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All tasks are pointed ✔️ 
- Pointing is fair ✔️ 
- All tasks have descriptions ✔️ ✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

According to the project requirements:

![image](https://user-images.githubusercontent.com/57421823/203739464-b60cd3a5-b903-4fcf-8eac-62cc53249a3d.png)

Therefore, 

- [ ] kindly add a screenshot of your kanban board to the description like this one:

![image](https://user-images.githubusercontent.com/57421823/203740140-38fc68be-d31b-40fa-9c6f-a1045d6f15d4.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Said-laasri** [comment]
@Meltrust thanks for the review

**Comment by NickEmma** [comment]
@Meltrust thank you for your review

**Comment by Meltrust** [comment]
Hi STUDENT_MENTION,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- Issue now has a screenshot✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Said-laasri** [comment]
@Meltrust thanks for the review on our project
